start: statement+

?statement: assign

assign: NAME "=" expr

expr: NAME
    | NUMBER
    | STRING
    | expr "+" expr   -> add
    | expr "-" expr   -> sub
    | expr "*" expr   -> mul
    | expr "/" expr   -> div
    | expr "//" expr  -> floordiv
    | expr "%" expr   -> mod
    | "(" expr ")"

NAME: /[a-zA-Z_][a-zA-Z0-9_]*/
NUMBER: /\d+/
STRING: /"([^"]*)"/

%import common.WS
%ignore WS
%import common.NEWLINE
%import common.INDENT
%import common.DEDENT